# Generated by Django 4.2 on 2024-03-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_user_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
